# Generated by Django 4.0.5 on 2022-06-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='JobSkills',
            new_name='JobSkill',
        ),
    ]
